insert into Client (id_client, name, surname, adres, value_contact) values (1, 'Georgeanna', 'Inès', '75 Lien Junction', 'KT1DHr43fgGcusZBzsmZpJKDATNDHmB1HQeK');
insert into Client (id_client, name, surname, adres, value_contact) values (2, 'Glenine', 'Gösta', '4 East Circle', 'KT1Nq2mDqrkeGVGyTBU7RWeJYP8SjWhVuJ39');
insert into Client (id_client, name, surname, adres, value_contact) values (3, 'Naoma', 'Liè', '37 Corry Lane', 'KT1FwUA39Wva4pVEmuPS4dD8FnzLGmohLeLa');
insert into Client (id_client, name, surname, adres, value_contact) values (4, 'Gothart', 'Mén', '88903 Del Sol Pass', 'KT1MQVBcwp7dyewhwaEvv2SZHaTSA95MW1gZ');
insert into Client (id_client, name, surname, adres, value_contact) values (5, 'Melisenda', 'Mélys', '7017 Thackeray Junction', 'KT1JwfNYfSpJFdk1neu3mT8W5QjytUMfk7ZQ');
insert into Client (id_client, name, surname, adres, value_contact) values (6, 'Ingelbert', 'Aurélie', '43 Hovde Hill', 'KT1EwaWBb2yNNJZZFmWLKzFHkB9tkcoz9hcq');
insert into Client (id_client, name, surname, adres, value_contact) values (7, 'Paten', 'Maéna', '19 Roth Place', 'KT1Bpsz3xWcPHEhm5ZLGB4VUqoHKv6WoyNsC');
insert into Client (id_client, name, surname, adres, value_contact) values (8, 'Vladamir', 'Ruì', '99 Walton Trail', 'KT1VnMUSnQQFSqN4d9wtXqEX7kaJohw9vRyx');
insert into Client (id_client, name, surname, adres, value_contact) values (9, 'Lonna', 'Håkan', '857 Parkside Court', 'KT1EETyHoJKiVCuzHa9mvncYfQHg8ZMfmFtA');
insert into Client (id_client, name, surname, adres, value_contact) values (10, 'Chester', 'Mårten', '89 Kim Crossing', 'KT1HC4yQ8nSFbpzyLRLYJyCS45PJgDAxWeY6');
insert into Client (id_client, name, surname, adres, value_contact) values (11, 'Josefina', 'André', '3537 Maple Wood Circle', 'KT1U69y7eg7ACyL6Ma9xCwLqebiGAiAxBA4P');
insert into Client (id_client, name, surname, adres, value_contact) values (12, 'Noella', 'Mélodie', '7238 Canary Point', 'KT1WcTUK3rDXySmp6bxAsLXKw5GW7dayh1ma');
insert into Client (id_client, name, surname, adres, value_contact) values (13, 'Clifford', 'Nuó', '50726 Lillian Avenue', 'KT1SCD72nK94EHkVLrKwzfQpu9ZGD24r3ns8');
insert into Client (id_client, name, surname, adres, value_contact) values (14, 'Merle', 'Miléna', '689 Farmco Plaza', 'KT19obbSW5uik25btD9zivVzTeoqFRW9gin7');
insert into Client (id_client, name, surname, adres, value_contact) values (15, 'Orton', 'Angélique', '90977 Division Drive', 'KT1RUfRnXSconCNad4FJptkZqwajQi7z1no3');
insert into Client (id_client, name, surname, adres, value_contact) values (16, 'Oona', 'Maïté', '40 Oneill Pass', 'KT1T9TDGEB1QDG9fKHYHNmuBd6TdgZ2NMf8r');
insert into Client (id_client, name, surname, adres, value_contact) values (17, 'Lucille', 'Camélia', '78 Service Hill', 'KT1GGNmHe7eC7WLKY3QiJJo3wqLAznQkZZMQ');
insert into Client (id_client, name, surname, adres, value_contact) values (18, 'Malinde', 'Lén', '213 Dwight Hill', 'KT1RYsDfrVtnAtCQHy8oPGuoV4V6BTgCBwYB');
insert into Client (id_client, name, surname, adres, value_contact) values (19, 'Wallis', 'Marie-françoise', '3 Prairie Rose Court', 'KT1VEJQRSLZX4YprgDcN6wQCz1uMi3k5sHyw');
insert into Client (id_client, name, surname, adres, value_contact) values (20, 'Bruno', 'Mén', '529 High Crossing Plaza', 'KT1PtVezXGVaacyfzJPzkQ5WAxaXPrUPzYAB');
insert into Client (id_client, name, surname, adres, value_contact) values (21, 'Georgi', 'Marlène', '69 Tomscot Plaza', 'KT1W849bpi1TsqWgmpYhNR6G6vnM28neYgSw');
insert into Client (id_client, name, surname, adres, value_contact) values (22, 'Geordie', 'Mélys', '466 Marquette Parkway', 'KT1Tz8BGU3AgEj95Tf9u9VxtXz7gbz7GuhC1');
insert into Client (id_client, name, surname, adres, value_contact) values (23, 'Justus', 'Thérèse', '59 Charing Cross Street', 'KT1JPiKq5dLRJccu6WmjGuh7Evbghis9yPdP');
insert into Client (id_client, name, surname, adres, value_contact) values (24, 'Quent', 'Thérèse', '0 Aberg Parkway', 'KT1Rz2spoLRwLfAKbN2GoRVEEKLwugzRhxnY');
insert into Client (id_client, name, surname, adres, value_contact) values (25, 'Demetra', 'Mylène', '18089 Sullivan Junction', 'KT1PWyAWH3Zb6qvysbZFmZkbZjVYuKjix7x3');
insert into Client (id_client, name, surname, adres, value_contact) values (26, 'Trenna', 'Adèle', '9 Fairfield Center', 'KT1HGtTZMPyG7pb76gh1BHBRRPXM7bBXz72f');
insert into Client (id_client, name, surname, adres, value_contact) values (27, 'Budd', 'Personnalisée', '7 Sycamore Parkway', 'KT1L44XW91mZgRL5jTaV9uzATtdSPAaDgx7m');
insert into Client (id_client, name, surname, adres, value_contact) values (28, 'Raymond', 'Annotée', '12224 Hazelcrest Alley', 'KT1M5eduzxr9usbxVnGBj3frU5PFzfddyw5H');
insert into Client (id_client, name, surname, adres, value_contact) values (29, 'Myrtia', 'Aimée', '1 Summerview Lane', 'KT1KqTrUyKhX4Ss1HoZKa9hHE3rSDtPUBd5h');
insert into Client (id_client, name, surname, adres, value_contact) values (30, 'Wileen', 'Irène', '6 Farmco Alley', 'KT1JzFicT3wACh2FsnPzZc5LiJUef2nFES3W');
insert into Client (id_client, name, surname, adres, value_contact) values (31, 'Annetta', 'Mylène', '9 Kensington Center', 'KT1PeJvTmC3j7Mc8znnWvfDWK7yNXzkGfBUf');
insert into Client (id_client, name, surname, adres, value_contact) values (32, 'Ediva', 'Maëlle', '635 Darwin Circle', 'KT1Ks4aUgaHok4Y9Dd59ns7Y1F9mUExsD6ib');
insert into Client (id_client, name, surname, adres, value_contact) values (33, 'Filmer', 'Mà', '65 Linden Trail', 'KT1HDP6aBXUN5KMh37ABrmREzGR7eZWAwZTb');
insert into Client (id_client, name, surname, adres, value_contact) values (34, 'Flory', 'Rachèle', '5757 John Wall Junction', 'KT1UeriS7AgmqaDtTgGZo9mxVm4n2hvkgNEw');
insert into Client (id_client, name, surname, adres, value_contact) values (35, 'Edan', 'Françoise', '1 Spaight Plaza', 'KT1PeqRSNpeAcVcnozHxxMqCXSgB2qx4UYDj');
insert into Client (id_client, name, surname, adres, value_contact) values (36, 'Casie', 'Torbjörn', '844 Myrtle Hill', 'KT1VyxnscqNpY4xvnDMdjc1YSxvJsnLLkF45');
insert into Client (id_client, name, surname, adres, value_contact) values (37, 'Benjamin', 'Torbjörn', '9 Cambridge Crossing', 'KT1Fo1VanPqGCkGQygdEN7TujjFfcGPQoqvK');
insert into Client (id_client, name, surname, adres, value_contact) values (38, 'Hillier', 'Faîtes', '481 Anhalt Junction', 'KT1E12mkgamWTFsRnaRATipRVN22a6672aki');
insert into Client (id_client, name, surname, adres, value_contact) values (39, 'Marita', 'Nadège', '17 Tennessee Street', 'KT1FcfBB7f46NFNxDRoPELCqYKyZkqixvTFP');
insert into Client (id_client, name, surname, adres, value_contact) values (40, 'Latisha', 'Faîtes', '93129 Ridgeview Street', 'KT1V72aCiWKhRp8HUgXFC4idnPRLDfoJU8Ei');
insert into Client (id_client, name, surname, adres, value_contact) values (41, 'Corty', 'Sélène', '4 Ilene Road', 'KT1N6KXb92dfLkWDmJsqHxm5najNGfwzHP23');
insert into Client (id_client, name, surname, adres, value_contact) values (42, 'Loralie', 'Liè', '7617 Warrior Alley', 'KT1L54KBK5YjnKFarXcjvWMqmwFBRGnRPTtU');
insert into Client (id_client, name, surname, adres, value_contact) values (43, 'Joanne', 'Eloïse', '99560 Fulton Drive', 'KT1P1kdh5o4FjiVV3bGxex5wmcHh2svAskKD');
insert into Client (id_client, name, surname, adres, value_contact) values (44, 'Sena', 'Béatrice', '753 Merrick Place', 'KT1BTCJUcAe2cxa7tfFUe8BkutwSCRk68zfE');
insert into Client (id_client, name, surname, adres, value_contact) values (45, 'Shurlock', 'Maëline', '6420 Melvin Hill', 'KT1XaKtifexsfxfay7yenchMhjSViwWbpkwv');
insert into Client (id_client, name, surname, adres, value_contact) values (46, 'Cookie', 'Cléopatre', '1226 Bluestem Park', 'KT1QqVVJ4bpS6pVagZxiC4mBTgsePEp8hiuY');
insert into Client (id_client, name, surname, adres, value_contact) values (47, 'Owen', 'Gaétane', '06 Bay Circle', 'KT1QBudvaaxiBxfCr4mnrVkrRHdPrcyj3CRv');
insert into Client (id_client, name, surname, adres, value_contact) values (48, 'Tanhya', 'Josée', '4 Summerview Court', 'KT1VDA5ZvgCbKfXCjT2AbP7JBwxooMmSD64e');
insert into Client (id_client, name, surname, adres, value_contact) values (49, 'Jeanette', 'Märta', '6002 Service Circle', 'KT1Ezavr437baQLdjm1KijtLggmCMZZ7sKBK');
insert into Client (id_client, name, surname, adres, value_contact) values (50, 'Guthrey', 'Daphnée', '35889 Drewry Place', 'KT1Mc8BUNJezCHP1DKS52NAtEWd4ZFpS1dcp');
