insert into Product (id_product, name_product, price_product, description_product) values (1, 'Thermometer Digital', 211, 'Teal');
insert into Product (id_product, name_product, price_product, description_product) values (2, 'Cake - Sheet Strawberry', 302, 'Maroon');
insert into Product (id_product, name_product, price_product, description_product) values (3, 'Cheese - Cheddar, Old White', 225, 'Fuscia');
insert into Product (id_product, name_product, price_product, description_product) values (4, 'Cakes Assorted', 212, 'Maroon');
insert into Product (id_product, name_product, price_product, description_product) values (5, 'Veal - Slab Bacon', 248, 'Orange');
insert into Product (id_product, name_product, price_product, description_product) values (6, 'Poppy Seed', 94, 'Puce');
insert into Product (id_product, name_product, price_product, description_product) values (7, 'Lemon Tarts', 172, 'Blue');
insert into Product (id_product, name_product, price_product, description_product) values (8, 'Cup - Paper 10oz 92959', 75, 'Red');
insert into Product (id_product, name_product, price_product, description_product) values (9, 'Table Cloth 90x90 White', 167, 'Green');
insert into Product (id_product, name_product, price_product, description_product) values (10, 'Oil - Macadamia', 263, 'Khaki');
insert into Product (id_product, name_product, price_product, description_product) values (11, 'Butter - Salted', 57, 'Indigo');
insert into Product (id_product, name_product, price_product, description_product) values (12, 'Kahlua', 175, 'Purple');
insert into Product (id_product, name_product, price_product, description_product) values (13, 'Table Cloth 72x144 White', 214, 'Orange');
insert into Product (id_product, name_product, price_product, description_product) values (14, 'Appetizer - Southwestern', 69, 'Aquamarine');
insert into Product (id_product, name_product, price_product, description_product) values (15, 'Wine - Red, Concha Y Toro', 246, 'Purple');
insert into Product (id_product, name_product, price_product, description_product) values (16, 'Dome Lid Clear P92008h', 247, 'Puce');
insert into Product (id_product, name_product, price_product, description_product) values (17, 'Horseradish Root', 66, 'Pink');
insert into Product (id_product, name_product, price_product, description_product) values (18, 'Kellogs All Bran Bars', 181, 'Mauv');
insert into Product (id_product, name_product, price_product, description_product) values (19, 'Cut Wakame - Hanawakaba', 326, 'Khaki');
insert into Product (id_product, name_product, price_product, description_product) values (20, 'Yoplait Drink', 111, 'Orange');
insert into Product (id_product, name_product, price_product, description_product) values (21, 'Compound - Passion Fruit', 315, 'Blue');
insert into Product (id_product, name_product, price_product, description_product) values (22, 'Horseradish Root', 165, 'Goldenrod');
insert into Product (id_product, name_product, price_product, description_product) values (23, 'Chocolate - White', 189, 'Teal');
insert into Product (id_product, name_product, price_product, description_product) values (24, 'Kumquat', 70, 'Violet');
insert into Product (id_product, name_product, price_product, description_product) values (25, 'Lid - 3oz Med Rec', 288, 'Puce');
insert into Product (id_product, name_product, price_product, description_product) values (26, 'Wine - Trimbach Pinot Blanc', 235, 'Mauv');
insert into Product (id_product, name_product, price_product, description_product) values (27, 'Jam - Strawberry, 20 Ml Jar', 264, 'Fuscia');
insert into Product (id_product, name_product, price_product, description_product) values (28, 'English Muffin', 117, 'Maroon');
insert into Product (id_product, name_product, price_product, description_product) values (29, 'Chick Peas - Canned', 211, 'Aquamarine');
insert into Product (id_product, name_product, price_product, description_product) values (30, 'Cauliflower', 77, 'Violet');
insert into Product (id_product, name_product, price_product, description_product) values (31, 'Fond - Chocolate', 174, 'Blue');
insert into Product (id_product, name_product, price_product, description_product) values (32, 'Sauce - Ranch Dressing', 310, 'Purple');
insert into Product (id_product, name_product, price_product, description_product) values (33, 'Longos - Burritos', 204, 'Green');
insert into Product (id_product, name_product, price_product, description_product) values (34, 'Beer - Tetleys', 148, 'Red');
insert into Product (id_product, name_product, price_product, description_product) values (35, 'Steampan - Foil', 299, 'Blue');
insert into Product (id_product, name_product, price_product, description_product) values (36, 'Chocolate - Pistoles, White', 52, 'Khaki');
insert into Product (id_product, name_product, price_product, description_product) values (37, 'Cumin - Ground', 179, 'Orange');
insert into Product (id_product, name_product, price_product, description_product) values (38, 'Bread Sour Rolls', 117, 'Fuscia');
insert into Product (id_product, name_product, price_product, description_product) values (39, 'Wine - Crozes Hermitage E.', 344, 'Orange');
insert into Product (id_product, name_product, price_product, description_product) values (40, 'Flour - Whole Wheat', 107, 'Mauv');
insert into Product (id_product, name_product, price_product, description_product) values (41, 'Syrup - Monin - Granny Smith', 339, 'Crimson');
insert into Product (id_product, name_product, price_product, description_product) values (42, 'Spice - Chili Powder Mexican', 305, 'Orange');
insert into Product (id_product, name_product, price_product, description_product) values (43, 'Dc - Sakura Fu', 98, 'Purple');
insert into Product (id_product, name_product, price_product, description_product) values (44, 'Bread - Bistro Sour', 200, 'Blue');
insert into Product (id_product, name_product, price_product, description_product) values (45, 'Beets - Mini Golden', 210, 'Turquoise');
insert into Product (id_product, name_product, price_product, description_product) values (46, 'Veal - Inside, Choice', 148, 'Crimson');
insert into Product (id_product, name_product, price_product, description_product) values (47, 'Crab Meat Claw Pasteurise', 312, 'Red');
insert into Product (id_product, name_product, price_product, description_product) values (48, 'Lamb Tenderloin Nz Fr', 72, 'Orange');
insert into Product (id_product, name_product, price_product, description_product) values (49, 'Steam Pan - Half Size Deep', 120, 'Orange');
insert into Product (id_product, name_product, price_product, description_product) values (50, 'Foie Gras', 240, 'Goldenrod');
