insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (1, 1, 'AmTrust Financial Services, Inc.', '0 Sutteridge Park', 'Puce');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (2, 2, 'Nuveen Build America Bond Fund', '42403 East Point', 'Maroon');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (3, 3, 'Wells Fargo & Company', '98195 Hudson Alley', 'Goldenrod');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (4, 4, 'Principal U.S. Small Cap Index ETF', '3 Kennedy Way', 'Fuscia');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (5, 5, 'Verizon Communications Inc.', '74 La Follette Lane', 'Violet');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (6, 6, 'Simpson Manufacturing Company, Inc.', '949 Calypso Park', 'Orange');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (7, 7, 'SLM Corporation', '1 Oak Park', 'Mauv');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (8, 8, 'First Trust South Korea AlphaDEX Fund', '63 Bluestem Junction', 'Indigo');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (9, 9, 'Winnebago Industries, Inc.', '67 Buhler Point', 'Mauv');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (10, 10, 'First Trust Mid Cap Core AlphaDEX Fund', '410 Messerschmidt Court', 'Green');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (11, 11, 'Qwest Corporation', '53468 Gina Trail', 'Turquoise');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (12, 12, 'Walt Disney Company (The)', '9 Hudson Alley', 'Blue');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (13, 13, 'Gabelli Dividend', '8169 Coleman Court', 'Orange');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (14, 14, 'My Size, Inc.', '54 Twin Pines Way', 'Green');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (15, 15, 'Motorcar Parts of America, Inc.', '70 Warbler Hill', 'Fuscia');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (16, 16, 'Independence Contract Drilling, Inc.', '11 Acker Junction', 'Aquamarine');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (17, 17, 'ProShares UltraPro Short NASDAQ Biotechnology', '7 Carey Way', 'Turquoise');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (18, 18, 'Orbital ATK, Inc.', '56245 Victoria Circle', 'Khaki');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (19, 19, 'Marathon Petroleum Corporation', '7 Jana Lane', 'Purple');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (20, 20, 'Impax Laboratories, Inc.', '353 Holmberg Way', 'Puce');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (21, 21, 'Cinemark Holdings Inc', '4 Westend Terrace', 'Red');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (22, 22, 'TransCanada Corporation', '8013 Carey Lane', 'Pink');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (23, 23, 'AzurRx BioPharma, Inc.', '96 Pierstorff Plaza', 'Pink');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (24, 24, 'The Long-Term Care ETF', '7 Sullivan Way', 'Maroon');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (25, 25, 'FCB Financial Holdings, Inc.', '4291 Pond Place', 'Crimson');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (26, 26, 'Lianluo Smart Limited', '2033 Dovetail Avenue', 'Green');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (27, 27, 'Potlatch Corporation', '78185 Florence Street', 'Khaki');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (28, 28, 'Eagle Point Credit Company Inc.', '57 Sachs Point', 'Khaki');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (29, 29, 'T-Mobile US, Inc.', '40 Bultman Park', 'Blue');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (30, 30, 'WisdomTree Japan Hedged SmallCap Equity Fund', '9252 Doe Crossing Park', 'Orange');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (31, 31, 'Pzena Investment Management Inc', '07953 Carioca Way', 'Orange');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (32, 32, 'Pieris Pharmaceuticals, Inc.', '44 Express Plaza', 'Crimson');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (33, 33, 'Sonoma Pharmaceuticals, Inc.', '317 Grim Pass', 'Pink');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (34, 34, 'Torchmark Corporation', '54194 Tomscot Drive', 'Fuscia');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (35, 35, 'Diodes Incorporated', '112 Ryan Crossing', 'Orange');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (36, 36, 'Vantage Energy Acquisition Corp.', '0 Trailsway Center', 'Green');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (37, 37, 'Community Health Systems, Inc.', '9 Morning Plaza', 'Mauv');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (38, 38, 'Chesapeake Lodging Trust', '763 Portage Alley', 'Crimson');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (39, 39, 'Customers Bancorp, Inc', '5516 Stephen Alley', 'Teal');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (40, 40, 'Global Indemnity Limited', '60 American Center', 'Crimson');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (41, 41, 'PowerShares KBW High Dividend Yield Financial Portfolio', '5638 Corscot Center', 'Khaki');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (42, 42, 'Novanta Inc.', '80 Barnett Terrace', 'Blue');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (43, 43, 'National Bank Holdings Corporation', '25476 North Parkway', 'Turquoise');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (44, 44, 'Resource Capital Corp.', '92 Marcy Plaza', 'Green');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (45, 45, 'MVC Capital, Inc.', '9 Maywood Pass', 'Maroon');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (46, 46, 'PowerShares Water Resources Portfolio', '3 Clarendon Parkway', 'Crimson');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (47, 47, 'Atlantica Yield plc', '981 Daystar Road', 'Violet');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (48, 48, 'Watts Water Technologies, Inc.', '1901 John Wall Trail', 'Orange');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (49, 49, 'ClearBridge Large Cap Growth ESG ETF', '250 Mcbride Street', 'Blue');
insert into Supplier (id_supplier, id_prod, name_supplier, adres, information) values (50, 50, 'Willamette Valley Vineyards, Inc.', '92 Grim Park', 'Teal');
