import sys
sys.path.append(r"C:\Users\Nike\Desktop\Scripts\Python\pgsql\bd")
import main_bd
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SupplierWindow(object):
    def setupUi(self, SupplierWindow):
        SupplierWindow.setObjectName("SupplierWindow")
        SupplierWindow.resize(428, 442)
        self.centralwidget = QtWidgets.QWidget(SupplierWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 40, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 100, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 160, 181, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 220, 181, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 280, 181, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 350, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(lambda: main_bd.add_value_request_supplier(self, self.lineEdit, self.lineEdit_2, self.lineEdit_3, self.lineEdit_4, self.lineEdit_5))

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setLineWidth(1)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 80, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setLineWidth(1)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(120, 140, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setLineWidth(1)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 200, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setLineWidth(1)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, 260, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setLineWidth(1)
        self.label_9.setObjectName("label_9")
        SupplierWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SupplierWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 428, 26))
        self.menubar.setObjectName("menubar")
        SupplierWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SupplierWindow)
        self.statusbar.setObjectName("statusbar")
        SupplierWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SupplierWindow)
        QtCore.QMetaObject.connectSlotsByName(SupplierWindow)

    def retranslateUi(self, SupplierWindow):
        _translate = QtCore.QCoreApplication.translate
        SupplierWindow.setWindowTitle(_translate("SupplierWindow", "SupplierWindow"))
        self.pushButton_2.setText(_translate("SupplierWindow", "Вставить"))
        self.label_5.setText(_translate("SupplierWindow", "ID"))
        self.label_6.setText(_translate("SupplierWindow", "id_product_FC"))
        self.label_7.setText(_translate("SupplierWindow", "name_supplier"))
        self.label_8.setText(_translate("SupplierWindow", "adres"))
        self.label_9.setText(_translate("SupplierWindow", "information"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SupplierWindow = QtWidgets.QMainWindow()
    ui = Ui_SupplierWindow()
    ui.setupUi(SupplierWindow)
    SupplierWindow.show()
    sys.exit(app.exec_())
